# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: gclouddemo
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
jobs:
  permissions:
    contents: 'read'
    id-token: 'write'
  
      steps:
      - uses: 'actions/checkout@v2'
  
      - uses: 'google-github-actions/auth@v1'
        with:
          #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-actions@psychic-sensor-387223.iam.gserviceaccount.com'
  
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'continuous-deployment'
          image: 'gcr.io/psychic-sensor-387223/gclouddemo'
  
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'